name: 发布 baidu-netdisk-sync 镜像

on:
  push:
    branches: [main]
    paths:
      - 'packages/srv/**'
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 配置 BuildX
        uses: docker/setup-buildx-action@v3

      - name: 登录 DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 提取版本号
        run: |
          VERSION=$(jq -r .version ./packages/srv/package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: 构建并推送镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./packages/srv/Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/baidu-netdisk-sync:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/baidu-netdisk-sync:v${{ env.VERSION }}
